           DISPLAY " " ERASE.
           DISPLAY "___________________".
           DISPLAY "____________________________".
           DISPLAY "___________________________________".
           DISPLAY "_________       ________________________".
           DISPLAY "_________ " "••••••" REVERSE
                   " ___________________________".
           DISPLAY "_________ " "•" REVERSE "     " "•" REVERSE
                   " _________     _______________".
           DISPLAY "_________ " "•" REVERSE "     " "•" REVERSE
                   " __    __ " "•" REVERSE "  " "••" REVERSE 
                   " __    ___   ___".
           DISPLAY "_________ " "•" REVERSE "     " "•" REVERSE
                   " _ " "••••" REVERSE " _ " "•" REVERSE " "
                   "•" REVERSE " ___ " "••••" REVERSE " _ "
                   "•••" REVERSE " ___".
           DISPLAY "_________ " "••••••" REVERSE " _ " "•" REVERSE
                   "    " "•" REVERSE "  " "••" REVERSE " ___ "
                   "•" REVERSE "    " "•" REVERSE "  " "•" REVERSE
                   "  " "•" REVERSE " __".
           DISPLAY "_________ " "•" REVERSE " ______ " "•" REVERSE
                   "    " "•" REVERSE "  " "••" REVERSE " ___ "
                   "••••••" REVERSE "  " "•" REVERSE " _____".
           DISPLAY "_________ " "•" REVERSE " ______ " "•" REVERSE
                   "    " "•" REVERSE "  " "•" REVERSE " " "•" REVERSE
                   " __ " "•" REVERSE "       " "•" REVERSE  "____".
           DISPLAY "_________ " "•" REVERSE " _______ " "••••" REVERSE
                   "   " "•" REVERSE "  " "••" REVERSE " _ "
                   "••••" REVERSE " _ " "•" REVERSE " ___".
           DISPLAY "______________________________________________".
           DISPLAY "__________________________________________".
           DISPLAY "_____________________________________".
           DISPLAY "____________________________".
           DISPLAY "Press any key" AT 2060.